language: python
puthon: 3.8
script: 
  - cd PythonApplication1
  - pytest
  - cd ..
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    repo: xsepower/FinalLaboratoryWork
    branch: master
    tags: false
